[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "evc/=lib/ethereum-vault-connector/src/",
    "a16z-erc4626-tests/=lib/erc4626-tests/"
]

